services:
  keycloak:
    container_name: keycloak-haller
    image: quay.io/keycloak/keycloak:26.2.4
    ports:
      - 9090:8080

    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

    networks:
       - spring-demo
    command: ["start-dev"]

networks:
  spring-demo:
    driver: bridge