server:
  port: 8081

spring:
  application:
    name: product-service

  r2dbc:
    url: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false

eureka:
  instance:
    prefer-ip-address: true

  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: "*"

logging:
  level:
    org.springframework.r2dbc: DEBUG
    org.springframework.data.r2dbc: DEBUG
    io.r2dbc.spi: DEBUG
    io.r2dbc.h2: DEBUG