pipeline {
    agent any

    environment {
        APP_NAME    = 'commande-service'
        SONAR_TOKEN = credentials('sonarqube-token')
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Checkout OK'
            }
        }
        stage('Build') {
            steps {
                dir('commande-service') {
                    sh 'mvn clean package -DskipTests --batch-mode --no-transfer-progress'
                }
            }
        }
        stage('Tests') {
            steps {
                dir('commande-service') {
                    sh 'mvn test --batch-mode --no-transfer-progress'
                }
            }
        }
        stage('SonarQube') {
            steps {
                dir('commande-service') {
                    withSonarQubeEnv('SonarQube') {
                        sh '''
                            mvn sonar:sonar \
                                -Dsonar.projectKey=commande-service \
                                -Dsonar.projectName="commande-service" \
                                --batch-mode \
                                --no-transfer-progress
                        '''
                    }
                }
            }
        }
        stage('Quality Gate') {
            steps {
                timeout(time: 5, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }
    }

    post {
        success { echo 'Pipeline réussi ✅' }
        failure { echo 'Pipeline en échec ❌' }
    }
}