server:
  port: 8081

spring:
  application:
    name: product-service

  config:
    import: "optional:configserver:"

  r2dbc:
    url: r2dbc:h2:mem:///testdb
    username: sa
    password: ''
  sql:
    init:
      mode: always

logging:
  level:
    org.springframework.r2dbc: DEBUG
    io.r2dbc.h2: DEBUG
    org.springframework.r2dbc.core: DEBUG

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true

management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: "*"