server:
  port: 8071

spring:
  application:
    name: product-service

  r2dbc:
    url: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false


management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: "*"

logging:
  level:
    org.springframework.r2dbc: DEBUG
    org.springframework.data.r2dbc: DEBUG
    io.r2dbc.spi: DEBUG
    io.r2dbc.h2: DEBUG