DROP TABLE IF EXISTS COMMANDES;
DROP TABLE IF EXISTS LIGNECOMMANDES;

CREATE TABLE COMMANDES (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID VARCHAR(255) NOT NULL,
    REFERENCE VARCHAR(100) NOT NULL,
    STATUT VARCHAR(50) NOT NULL DEFAULT 'CREEE',
    DATE_COMMANDE TIMESTAMP NOT NULL
);

CREATE TABLE LIGNECOMMANDES (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    COMMANDE_ID BIGINT NOT NULL REFERENCES COMMANDES(ID) ON DELETE CASCADE,
    ARTICLE VARCHAR(255) NOT NULL,
    QUANTITE INT NOT NULL
);