DROP TABLE IF EXISTS COMMANDES;

CREATE TABLE COMMANDES (
    ID            BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID       VARCHAR(255) NOT NULL,
    REFERENCE     VARCHAR(100) NOT NULL,
    STATUT        VARCHAR(50)  NOT NULL DEFAULT 'CREEE',
    DATE_COMMANDE TIMESTAMP    NOT NULL
);