spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost/dummy
          issuer-uri: http://localhost/dummy

  mail:
    host: localhost
    port: 25
    username: test
    password: test
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

    cloud:
      discovery:
        enabled: false


  config:
    import: "optional:configserver:"

  r2dbc:
    url: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

  h2:
    console:
      enabled: true

eureka:
  client:
    enabled: false


